{{ config(
    materialized='table',
    post_hook=[
        "COPY {{ this }} TO 's3://pse-clean/{{ this.name }}.parquet'",
        "COPY {{ this }} TO 's3://pse-clean/{{ this.name }}.csv' (FORMAT CSV, HEADER)"
    ]
) }}

SELECT
    , TRY_CAST("Date" AS DATE) AS "Date"
    , "Symbol", "Sector", "Industry"
    , TRY_CAST("Open" AS NUMERIC) AS "Open"
    , TRY_CAST("High" AS NUMERIC) AS "High"
    , TRY_CAST("Low" AS NUMERIC) AS "Low"
    , TRY_CAST("Close" AS NUMERIC) AS "Close"
    , TRY_CAST("Chg" AS NUMERIC) AS "Chg"
    , TRY_CAST(ROUND("Value", 0) AS BIGINT) AS "Value"
    , TRY_CAST(ROUND("Volume", 0) AS BIGINT) AS "Volume"
    , TRY_CAST(ROUND("MA20", 2) AS NUMERIC) AS "MA20"
    , TRY_CAST(ROUND("MA60", 2) AS NUMERIC) AS "MA60"
    , TRY_CAST(ROUND("MA240", 2) AS NUMERIC) AS "MA240"
    , TRY_CAST(ROUND("RSI20", 2) AS NUMERIC) AS "RSI20"
    , TRY_CAST(ROUND("RSI60", 2) AS NUMERIC) AS "RSI60"
    , TRY_CAST(ROUND("RSI240", 2) AS NUMERIC) AS "RSI240"
    , TRY_CAST(ROUND("Month High", 2) AS NUMERIC) AS "Month High"
    , TRY_CAST(ROUND("Month Low", 2) AS NUMERIC) AS "Month Low"
    , TRY_CAST(ROUND("Quarter High", 2) AS NUMERIC) AS "Quarter High"
    , TRY_CAST(ROUND("Quarter Low", 2) AS NUMERIC) AS "Quarter Low"
    , TRY_CAST(ROUND("Year High", 2) AS NUMERIC) AS "Year High"
    , TRY_CAST(ROUND("Year Low", 2) AS NUMERIC) AS "Year Low"
    , TRY_CAST(ROUND("All Time High", 2) AS NUMERIC) AS "All Time High"
    , TRY_CAST(ROUND("All Time Low", 2) AS NUMERIC) AS "All Time Low"
    , TRY_CAST(ROUND("Market RSI20", 2) AS NUMERIC) AS "Market RSI20"
    , TRY_CAST(ROUND("Market RSI60", 2) AS NUMERIC) AS "Market RSI60"
    , TRY_CAST(ROUND("Market RSI240", 2) AS NUMERIC) AS "Market RSI240"
    , TRY_CAST(ROUND("Sector RSI20", 2) AS NUMERIC) AS "Sector RSI20"
    , TRY_CAST(ROUND("Sector RSI60", 2) AS NUMERIC) AS "Sector RSI60"
    , TRY_CAST(ROUND("Sector RSI240", 2) AS NUMERIC) AS "Sector RSI240"
    , TRY_CAST(ROUND("Industry RSI20", 2) AS NUMERIC) AS "Industry RSI20"
    , TRY_CAST(ROUND("Industry RSI60", 2) AS NUMERIC) AS "Industry RSI60"
    , TRY_CAST(ROUND("Industry RSI240", 2) AS NUMERIC) AS "Industry RSI240"
    , TRY_CAST(ROUND("Relative Month High", 2) AS NUMERIC) AS "Relative Month High"
    , TRY_CAST(ROUND("Relative Month Low", 2) AS NUMERIC) AS "Relative Month Low"
    , TRY_CAST(ROUND("Relative Quarter High", 2) AS NUMERIC) AS "Relative Quarter High"
    , TRY_CAST(ROUND("Relative Quarter Low", 2) AS NUMERIC) AS "Relative Quarter Low"
    , TRY_CAST(ROUND("Relative Year High", 2) AS NUMERIC) AS "Relative Year High"
    , TRY_CAST(ROUND("Relative Year Low", 2) AS NUMERIC) AS "Relative Year Low"
    , TRY_CAST(ROUND("Relative All Time High", 2) AS NUMERIC) AS "Relative All Time High"
    , TRY_CAST(ROUND("Relative All Time Low", 2) AS NUMERIC) AS "Relative All Time Low"
    , TRY_CAST(ROUND("Relative Market RSI 20", 2) AS NUMERIC) AS "Relative Market RSI 20"
    , TRY_CAST(ROUND("Relative Market RSI 60", 2) AS NUMERIC) AS "Relative Market RSI 60"
    , TRY_CAST(ROUND("Relative Market RSI 240", 2) AS NUMERIC) AS "Relative Market RSI 240"
    , TRY_CAST(ROUND("Relative Sector RSI 20", 2) AS NUMERIC) AS "Relative Sector RSI 20"
    , TRY_CAST(ROUND("Relative Sector RSI 60", 2) AS NUMERIC) AS "Relative Sector RSI 60"
    , TRY_CAST(ROUND("Relative Sector RSI 240", 2) AS NUMERIC) AS "Relative Sector RSI 240"
    , TRY_CAST(ROUND("Relative Industry RSI 20", 2) AS NUMERIC) AS "Relative Industry RSI 20"
    , TRY_CAST(ROUND("Relative Industry RSI 60", 2) AS NUMERIC) AS "Relative Industry RSI 60"
    , TRY_CAST(ROUND("Relative Industry RSI 240", 2) AS NUMERIC) AS "Relative Industry RSI 240"

FROM {{ ref('pse_clean_price_full') }}
WHERE YEAR(Date) = 2026