= Table.TransformColumnTypes(#"Promoted Headers",{
	{"Date", type date},
	{"Symbol", type text},
	{"Sector", type text},
	{"Industry", type text},
	{"Chg", type number},
	{"Open", type number},
	{"High", type number},
	{"Low", type number},
	{"Close", type number},
	{"Value", Int64.Type},
	{"Volume", Int64.Type},
	{"High5", type number},
	{"High10", type number},
	{"High20", type number},
	{"High30", type number},
	{"High60", type number},
	{"High120", type number},
	{"High240", type number},
	{"HighAll", type number},
	{"Low5", type number},
	{"Low10", type number},
	{"Low20", type number},
	{"Low30", type number},
	{"Low60", type number},
	{"Low120", type number},
	{"Low240", type number},
	{"LowAll", type number},
	{"MA5", type number},
	{"MA10", type number},
	{"MA20", type number},
	{"MA30", type number},
	{"MA60", type number},
	{"MA120", type number},
	{"MA240", type number},
	{"RSI5", type number},
	{"RSI10", type number},
	{"RSI20", type number},
	{"RSI30", type number},
	{"RSI60", type number},
	{"RSI120", type number},
	{"RSI240", type number},
	{"MarketRSI5", type number},
	{"MarketRSI10", type number},
	{"MarketRSI20", type number},
	{"MarketRSI30", type number},
	{"MarketRSI60", type number},
	{"MarketRSI120", type number},
	{"MarketRSI240", type number},
	{"SectorRSI5", type number},
	{"SectorRSI10", type number},
	{"SectorRSI20", type number},
	{"SectorRSI30", type number},
	{"SectorRSI60", type number},
	{"SectorRSI120", type number},
	{"SectorRSI240", type number},
	{"IndustryRSI5", type number},
	{"IndustryRSI10", type number},
	{"IndustryRSI20", type number},
	{"IndustryRSI30", type number},
	{"IndustryRSI60", type number},
	{"IndustryRSI120", type number},
	{"IndustryRSI240", type number},
	{"RelativeHigh5", type number},
	{"RelativeHigh10", type number},
	{"RelativeHigh20", type number},
	{"RelativeHigh30", type number},
	{"RelativeHigh60", type number},
	{"RelativeHigh120", type number},
	{"RelativeHigh240", type number},
	{"RelativeHighAll", type number},
	{"RelativeLow5", type number},
	{"RelativeLow10", type number},
	{"RelativeLow20", type number},
	{"RelativeLow30", type number},
	{"RelativeLow60", type number},
	{"RelativeLow120", type number},
	{"RelativeLow240", type number},
	{"RelativeLowAll", type number},
	{"RelativeMarketRSI5", type number},
	{"RelativeMarketRSI10", type number},
	{"RelativeMarketRSI20", type number},
	{"RelativeMarketRSI30", type number},
	{"RelativeMarketRSI60", type number},
	{"RelativeMarketRSI120", type number},
	{"RelativeMarketRSI240", type number},
	{"RelativeSectorRSI5", type number},
	{"RelativeSectorRSI10", type number},
	{"RelativeSectorRSI20", type number},
	{"RelativeSectorRSI30", type number},
	{"RelativeSectorRSI60", type number},
	{"RelativeSectorRSI120", type number},
	{"RelativeSectorRSI240", type number},
	{"RelativeIndustryRSI5", type number},
	{"RelativeIndustryRSI10", type number},
	{"RelativeIndustryRSI20", type number},
	{"RelativeIndustryRSI30", type number},
	{"RelativeIndustryRSI60", type number},
	{"RelativeIndustryRSI120", type number},	
	{"RelativeIndustryRSI240", type number}
})