= Table.TransformColumnTypes(#"Promoted Headers",{
	{"Sector", type text},
	{"Industry", type text},
	{"Count", Int64.Type},
	{"Turnover", Int64.Type},
	{"MarketCap", Int64.Type},
	{"Assets", Int64.Type},
	{"Liabilities", Int64.Type},
	{"Equity", Int64.Type},
	{"Revenue", Int64.Type},
	{"Income", Int64.Type},
	{"AvgRSI5", type number},
	{"AvgRSI10", type number},
	{"AvgRSI20", type number},
	{"AvgRSI30", type number},
	{"AvgRSI60", type number},
	{"AvgRSI120", type number},
	{"AvgRSI240", type number},
	{"BreadthMA5", type number},
	{"BreadthMA10", type number},
	{"BreadthMA20", type number},
	{"BreadthMA30", type number},
	{"BreadthMA60", type number},
	{"BreadthMA120", type number},
	{"BreadthMA240", type number},
	{"GrowthRevenue", type number},
	{"GrowthIncome", type number},
	{"MarginIncome", type number},
	{"ReturnOnAssets", type number},
	{"ReturnOnEquity", type number},
	{"PSRatio", type number},
	{"PERatio", type number},
	{"PBVRatio", type number},
	{"PSGRatio", type number},
	{"PEGRatio", type number},
	{"RankGrowthRevenue", Int64.Type},
	{"RankGrowthIncome", Int64.Type},
	{"RankMargin", Int64.Type},
	{"RankROA", Int64.Type},
	{"RankROE", Int64.Type},
	{"RankPSRatio", Int64.Type},
	{"RankPERatio", Int64.Type},
	{"RankPBVRatio", Int64.Type},
	{"RankBreadth5", Int64.Type},
	{"RankBreadth10", Int64.Type},
	{"RankBreadth20", Int64.Type},
	{"RankBreadth30", Int64.Type},
	{"RankBreadth60", Int64.Type},
	{"RankBreadth120", Int64.Type},
	{"RankBreadth240", Int64.Type},
	{"RankProfitability", type number},
	{"RankValuation", type number},
	{"RankBreadth", type number},
	{"RankOverall", type number}
})