name: PSE Pipeline

on:
    schedule:
        - cron: '0 22 * * 0-4'
    workflow_dispatch: 

jobs:
    run-pipeline:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
          
            - name: Build Docker image
              run: docker build -t pse-pipeline:v01 .
              working-directory: ${{ github.workspace }}

            # - name: Run price pipeline
              # env:
                # SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                # SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
              # run: |
                # docker run --rm \
                  # -e SUPABASE_URL=$SUPABASE_URL \
                  # -e SUPABASE_KEY=$SUPABASE_KEY \
                  # pse-pipeline:v01 uv run python pse_pipeline_price.py

            # - name: Run meta pipeline
              # env:
                # SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                # SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
              # run: |
                # docker run --rm \
                  # -e SUPABASE_URL=$SUPABASE_URL \
                  # -e SUPABASE_KEY=$SUPABASE_KEY \
                  # pse-pipeline:v01 uv run python pse_pipeline_meta.py

            - name: Run duckdb processing
              env:
                SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
                S3_KEY: ${{ secrets.SUPABASE_S3_ACCESS_KEY_ID }}
                S3_SECRET: ${{ secrets.SUPABASE_S3_SECRET_ACCESS_KEY }}
              run: |
                docker run --rm \
                  -e SUPABASE_URL=$SUPABASE_URL \
                  -e SUPABASE_KEY=$SUPABASE_KEY \
                  -e S3_KEY=$SUPABASE_S3_ACCESS_KEY_ID \
                  -e S3_SECRET=$SUPABASE_S3_SECRET_ACCESS_KEY \
                  pse-pipeline:v01 uv run python pse_pipeline_duckdb.py
